[project]
name = "qrt-aapf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "lightgbm>=4.7.0",
    "matplotlib>=3.11.2",
    "mlflow>=3.16.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "pytest>=9.1.1",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "statsmodels>=0.15.0",
]

[build-system]
requires = ["uv_build>=0.12.19,<0.13"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "qrt"
